version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "movies_db"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123qwe"
      POSTGRES_HOST: "127.0.0.1"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
      context: app
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./app/example/static:/opt/app/static
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./app/example/static:/opt/app/static
    depends_on:
      - service

volumes:
  postgres_data:
#    external: True