version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "movies_db"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123qwe"
      POSTGRES_HOST: "127.0.0.1"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
      context: app
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./app/example/static:/opt/app/static
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./app/example/static:/opt/app/static
    depends_on:
      - service

  elastic:
      image: elasticsearch:8.4.1
      ports:
        - "9200:9200"
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms200m -Xmx200m
        - xpack.security.enabled=false
      volumes:
        - elasticsearch_data:/elasticsearch/data
      depends_on:
          - db

  etl_service:
    build:
          context: etl
    environment:
          HOST: db
          HOSTES: elastic
    depends_on:
      - elastic
    volumes:
      - etl_data:/etl/data
    entrypoint: ["python", "connection.py"]


volumes:
  elasticsearch_data:
  etl_data:
  postgres_data:
#    external: True